# Data Preprocessing

In [206]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,precision_score,recall_score,confusion_matrix

In [207]:
data = pd.read_csv(r"C:\Users\ASUS\Desktop\Mini Project\Ensemble_prediction_system\deepfake_features.csv")
data.head()

,label,m1_real,m1_fake,m2_real,m2_fake,m3_real,m3_fake,m4_real,m4_fake,m5_real,m5_fake
0,1,0.999208,0.000792,0.999214,0.000786,0.999507,0.000493,0.664097,0.335903,0.206790,0.793210
1,1,0.999407,0.000593,0.999309,0.000691,0.974394,0.025606,0.732185,0.267815,0.153708,0.846292
2,1,0.999466,0.000534,0.999398,0.000602,0.999536,0.000464,0.952463,0.047537,0.129481,0.870519
3,1,0.999497,0.000503,0.999468,0.000532,0.999413,0.000587,0.544896,0.455104,0.687875,0.312125
4,1,0.999296,0.000704,0.999164,0.000836,0.974307,0.025693,0.039172,0.960828,0.296768,0.703232

In [208]:
data.isnull().sum()

label      0
m1_real    0
m1_fake    0
m2_real    0
m2_fake    0
m3_real    0
m3_fake    0
m4_real    0
m4_fake    0
m5_real    0
m5_fake    0
dtype: int64

In [209]:
data.duplicated().sum()

0

In [210]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    2000 non-null   int64
 1   m1_real  2000 non-null   float64
 2   m1_fake  2000 non-null   float64
 3   m2_real  2000 non-null   float64
 4   m2_fake  2000 non-null   float64
 5   m3_real  2000 non-null   float64
 6   m3_fake  2000 non-null   float64
 7   m4_real  2000 non-null   float64
 8   m4_fake  2000 non-null   float64
 9   m5_real  2000 non-null   float64
 10  m5_fake  2000 non-null   float64
dtypes: float64(10), int64(1)
memory usage: 172.0 KB

In [211]:
data.describe()

,label,m1_real,m1_fake,m2_real,m2_fake,m3_real,m3_fake,m4_real,m4_fake,m5_real,m5_fake
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,0.500000,0.993595,0.006405,0.991637,0.008363,0.959779,0.040221,0.759537,0.240463,0.542001,0.457999
std,0.500125,0.044390,0.044390,0.061403,0.061403,0.134299,0.134299,0.296135,0.296135,0.320262,0.320262
min,0.000000,0.271936,0.000352,0.058018,0.000399,0.004191,0.000425,0.011303,0.000498,0.040342,0.085072
25%,0.000000,0.999068,0.000491,0.998963,0.000552,0.995857,0.000451,0.580238,0.009195,0.220524,0.116584
50%,0.500000,0.999396,0.000604,0.999322,0.000678,0.999471,0.000529,0.909730,0.090270,0.565272,0.434728
75%,1.000000,0.999509,0.000932,0.999448,0.001037,0.999549,0.004143,0.990805,0.419762,0.883416,0.779476
max,1.000000,0.999648,0.728064,0.999601,0.941982,0.999575,0.995809,0.999502,0.988697,0.914928,0.959658

In [212]:
X = data.drop('label',axis=1)
y = data['label']

In [213]:
display(X,y)

,m1_real,m1_fake,m2_real,m2_fake,m3_real,m3_fake,m4_real,m4_fake,m5_real,m5_fake
0,0.999208,0.000792,0.999214,0.000786,0.999507,0.000493,0.664097,0.335903,0.206790,0.793210
1,0.999407,0.000593,0.999309,0.000691,0.974394,0.025606,0.732185,0.267815,0.153708,0.846292
2,0.999466,0.000534,0.999398,0.000602,0.999536,0.000464,0.952463,0.047537,0.129481,0.870519
3,0.999497,0.000503,0.999468,0.000532,0.999413,0.000587,0.544896,0.455104,0.687875,0.312125
4,0.999296,0.000704,0.999164,0.000836,0.974307,0.025693,0.039172,0.960828,0.296768,0.703232
...,...,...,...,...,...,...,...,...,...,...
1995,0.999490,0.000510,0.999436,0.000564,0.999551,0.000449,0.997919,0.002081,0.703734,0.296266
1996,0.999578,0.000422,0.999511,0.000489,0.999568,0.000432,0.999299,0.000701,0.871746,0.128254
1997,0.999532,0.000468,0.999476,0.000524,0.999409,0.000591,0.899491,0.100509,0.900136,0.099864
1998,0.999204,0.000796,0.999094,0.000906,0.999566,0.000434,0.990774,0.009226,0.908891,0.091109
1999,0.999466,0.000534,0.999397,0.000603,0.999556,0.000444,0.958574,0.041426,0.472649,0.527351

0       1
1       1
2       1
3       1
4       1
       ..
1995    0
1996    0
1997    0
1998    0
1999    0
Name: label, Length: 2000, dtype: int64

In [214]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.1,random_state=42)

In [215]:
display(x_train,x_test,y_train,y_test)

,m1_real,m1_fake,m2_real,m2_fake,m3_real,m3_fake,m4_real,m4_fake,m5_real,m5_fake
1872,0.999122,0.000878,0.999066,0.000934,0.999560,0.000440,0.997607,0.002393,0.912015,0.087985
526,0.999284,0.000716,0.999212,0.000788,0.975991,0.024009,0.953931,0.046069,0.908322,0.091678
173,0.999451,0.000549,0.999419,0.000581,0.999558,0.000442,0.953723,0.046277,0.093421,0.906579
720,0.999511,0.000489,0.999453,0.000547,0.999513,0.000487,0.744933,0.255067,0.189974,0.810026
414,0.998518,0.001482,0.998324,0.001676,0.982641,0.017359,0.073109,0.926891,0.085786,0.914214
...,...,...,...,...,...,...,...,...,...,...
1130,0.999523,0.000477,0.999442,0.000558,0.999456,0.000544,0.996837,0.003163,0.910131,0.089869
1294,0.999552,0.000448,0.999470,0.000530,0.999509,0.000491,0.200059,0.799941,0.907857,0.092143
860,0.998551,0.001449,0.998365,0.001635,0.987291,0.012709,0.963569,0.036431,0.255624,0.744376
1459,0.998165,0.001835,0.998103,0.001897,0.997391,0.002609,0.942092,0.057908,0.890188,0.109812
1126,0.999390,0.000610,0.999378,0.000622,0.998308,0.001692,0.997882,0.002118,0.830891,0.169109

,m1_real,m1_fake,m2_real,m2_fake,m3_real,m3_fake,m4_real,m4_fake,m5_real,m5_fake
1860,0.998555,0.001445,0.998457,0.001543,0.977954,0.022046,0.977361,0.022639,0.337272,0.662728
353,0.999350,0.000650,0.999278,0.000722,0.999549,0.000451,0.947253,0.052747,0.055488,0.944512
1333,0.999501,0.000499,0.999461,0.000539,0.993922,0.006078,0.442881,0.557119,0.644963,0.355037
905,0.999574,0.000426,0.999516,0.000484,0.999174,0.000826,0.997138,0.002862,0.213895,0.786105
1289,0.999523,0.000477,0.999457,0.000543,0.999372,0.000628,0.447405,0.552595,0.881055,0.118945
...,...,...,...,...,...,...,...,...,...,...
462,0.998944,0.001056,0.998733,0.001267,0.996864,0.003136,0.988467,0.011533,0.198884,0.801116
1105,0.997828,0.002172,0.996944,0.003056,0.891478,0.108522,0.386003,0.613997,0.490499,0.509501
855,0.999592,0.000408,0.999547,0.000453,0.999517,0.000483,0.277086,0.722914,0.063103,0.936897
693,0.999555,0.000445,0.999476,0.000524,0.999571,0.000429,0.998627,0.001373,0.194583,0.805417
1551,0.996859,0.003141,0.995957,0.004043,0.867426,0.132574,0.833603,0.166397,0.317815,0.682185

1872    0
526     1
173     1
720     1
414     1
       ..
1130    0
1294    0
860     1
1459    0
1126    0
Name: label, Length: 1800, dtype: int64

1860    0
353     1
1333    0
905     1
1289    0
       ..
462     1
1105    0
855     1
693     1
1551    0
Name: label, Length: 200, dtype: int64

In [216]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

# Random Forest

In [218]:
from sklearn.ensemble import RandomForestClassifier

In [219]:
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [220]:
y_pred = model_rf.predict(x_test)

In [221]:
accuracy = accuracy_score(y_test,y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test,y_pred)
f1 = f1_score(y_test,y_pred)

In [222]:
print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1-score:",f1)

Accuracy: 0.78
Precision: 0.7956989247311828
Recall: 0.7474747474747475
F1-score: 0.7708333333333334

In [223]:
importance = model_rf.feature_importances_
feature_names = X.columns

feat_imp = pd.Series(importance, index=feature_names).sort_values(ascending=False)
print(feat_imp)

m5_fake    0.296299
m5_real    0.256611
m4_fake    0.062077
m4_real    0.060869
m3_fake    0.059821
m3_real    0.055061
m2_fake    0.053299
m2_real    0.053186
m1_real    0.051638
m1_fake    0.051138
dtype: float64

# XGBoost

In [225]:
# pip install xgboost

In [226]:
from xgboost import XGBClassifier

In [227]:
model_xg = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    use_label_encoder=False,
    eval_metric='logloss'
)
model_xg.fit(x_train,y_train)

C:\Users\ASUS\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [18:11:57] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [228]:
y_pred_xg = model_xg.predict(x_test)

In [229]:
accuracy = accuracy_score(y_test,y_pred_xg)
precision = precision_score(y_test,y_pred_xg)
recall = recall_score(y_test,y_pred_xg)
f1 = f1_score(y_test,y_pred_xg)

In [230]:
print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1-score:",f1)

Accuracy: 0.8
Precision: 0.8172043010752689
Recall: 0.7676767676767676
F1-score: 0.7916666666666666

In [231]:
importance = model_xg.feature_importances_
feature_names = X.columns

feat_imp = pd.Series(importance, index=feature_names).sort_values(ascending=False)
print(feat_imp)

m5_real    0.314153
m5_fake    0.262622
m2_real    0.055369
m1_fake    0.054754
m2_fake    0.054744
m1_real    0.054586
m3_fake    0.052615
m4_fake    0.052412
m4_real    0.050965
m3_real    0.047780
dtype: float32

# LightGBM

In [233]:
# pip install lightgbm

In [234]:
from lightgbm import LGBMClassifier

In [235]:
lgbm = LGBMClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

lgbm.fit(x_train, y_train)

[LightGBM] [Info] Number of positive: 901, number of negative: 899
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000167 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 1800, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500556 -> initscore=0.002222
[LightGBM] [Info] Start training from score 0.002222
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, max_depth=4,
               n_estimators=200, random_state=42, subsample=0.8)

In [236]:
y_pred_lgbm = lgbm.predict(x_test)

In [237]:
accuracy = accuracy_score(y_test,y_pred_lgbm)
precision = precision_score(y_test,y_pred_lgbm)
recall = recall_score(y_test,y_pred_lgbm)
f1 = f1_score(y_test,y_pred_lgbm)

In [238]:
print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1-score:",f1)

Accuracy: 0.795
Precision: 0.8085106382978723
Recall: 0.7676767676767676
F1-score: 0.7875647668393783

In [239]:
importance = lgbm.feature_importances_
feature_names = X.columns

feat_imp = pd.Series(importance, index=feature_names).sort_values(ascending=False)
print(feat_imp)

m5_real    403
m5_fake    314
m4_real    270
m3_real    227
m3_fake    198
m4_fake    184
m2_real    153
m2_fake    140
m1_real    138
m1_fake    102
dtype: int32

# Logistic Regression

In [241]:
from sklearn.linear_model import LogisticRegression

In [242]:
lr = LogisticRegression(max_iter=1000)

lr.fit(x_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [243]:
y_pred_lr = lr.predict(x_test_scaled)

In [244]:
accuracy = accuracy_score(y_test,y_pred_lr)
precision = precision_score(y_test,y_pred_lr)
recall = recall_score(y_test,y_pred_lr)
f1 = f1_score(y_test,y_pred_lr)

In [245]:
print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1-score:",f1)

Accuracy: 0.805
Precision: 0.8191489361702128
Recall: 0.7777777777777778
F1-score: 0.7979274611398963

# SVM (RBF kernel)

In [247]:
from sklearn.svm import SVC

In [248]:
svm = SVC(
    kernel='rbf',   
    C=1.0,
    gamma='scale',
    probability=True
)
svm.fit(x_train_scaled, y_train)

SVC(probability=True)

In [249]:
y_pred_svm = svm.predict(x_test_scaled)

In [250]:
accuracy = accuracy_score(y_test,y_pred_svm)
precision = precision_score(y_test,y_pred_svm)
recall = recall_score(y_test,y_pred_svm)
f1 = f1_score(y_test,y_pred_svm)

In [251]:
print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1-score:",f1)

Accuracy: 0.795
Precision: 0.8020833333333334
Recall: 0.7777777777777778
F1-score: 0.7897435897435897

# Comparative Analysis

In [253]:
results = []

def evaluate_model(name, y_true, y_pred):
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall": recall_score(y_true, y_pred),
        "F1 Score": f1_score(y_true, y_pred)
    })


# Random Forest
evaluate_model("Random Forest", y_test, y_pred)

# XGBoost
evaluate_model("XGBoost", y_test, y_pred_xg)

# LightGBM
evaluate_model("LightGBM", y_test, y_pred_lgbm)

# Logistic Regression
evaluate_model("Logistic Regression", y_test, y_pred_lr)

# SVM
evaluate_model("SVM (RBF)", y_test, y_pred_svm)


results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="F1 Score", ascending=False)

results_df.style.highlight_max(color='lightgreen')

# Meta-Meta Ensemble

In [255]:
from sklearn.ensemble import VotingClassifier

voting = VotingClassifier(
    estimators=[
        ('lr', lr),
        ('xgb', model_xg),
        ('svm', svm)
    ],
    voting='soft'   # IMPORTANT
)

voting.fit(x_train_scaled, y_train)
y_pred_voting = voting.predict(x_test_scaled)

C:\Users\ASUS\anaconda3\Lib\site-packages\xgboost\training.py:200: UserWarning: [18:11:58] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [256]:
accuracy = accuracy_score(y_test,y_pred_voting)
precision = precision_score(y_test,y_pred_voting)
recall = recall_score(y_test,y_pred_voting)
f1 = f1_score(y_test,y_pred_voting)

print("Accuracy:",accuracy)
print("Precision:",precision)
print("Recall:",recall)
print("F1-score:",f1)

Accuracy: 0.805
Precision: 0.8191489361702128
Recall: 0.7777777777777778
F1-score: 0.7979274611398963

# save the best model

In [302]:
import joblib

# Save model
joblib.dump(lr, "meta_model_lr.pkl")

['meta_model_lr.pkl']